# Generated by Django 4.1.13 on 2024-04-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0017_rdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_titre', models.CharField(max_length=255)),
                ('property_description', models.TextField()),
                ('property_surface', models.IntegerField()),
                ('property_dispo', models.CharField(max_length=255)),
                ('property_prix', models.IntegerField()),
                ('image', models.ImageField(default='default_image.jpg', upload_to='property_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.category')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userAuth.service')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idImage', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='userAuth.property')),
            ],
        ),
    ]
