# Generated by Django 4.1.13 on 2024-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0019_propertyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='property_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
